---
abstract: 'a modern perl interactive shell'
author:
  - 'Matt S Trout - mst (at) shadowcatsystems.co.uk (L<http://www.shadowcatsystems.co.uk/>)'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-REPL
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  B::Concise: 0
  Devel::Peek: 0
  File::HomeDir: 0
  File::Spec: 0
  Moose: 0.74
  MooseX::AttributeHelpers: 0.16
  MooseX::Getopt: 0.18
  MooseX::Object::Pluggable: 0.0009
  Task::Weaken: 0
  Term::ANSIColor: 0
  Term::ReadLine: 0
  namespace::clean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.003005
